setup_mode = false
sim_mode = false
solve_mode = false
fov_mm = [
    25.6,
    12.8,
    12.8,
]
matrix_size = [
    512,
    256,
    256,
]
spectral_width_khz = 100.0
rf_duration_us = 100
diffusion_ramp_time_us = 400
imaging_ramp_time_us = 200
phase_enc_dur_ms = 0.2
little_delta_ms = 2.5
rep_time_ms = 100.0
g_limit_tpm = 2.2
post_diff2_delay_ms = 0.2
cs_table = "/Users/Wyatt/scratch/260316_00/stream_CS256_8x_pa18_pb54"
bvec_table = "/Users/Wyatt/scratch/260316_00/6_shell_144_6b0.txt"
target_bvalues = [
    0.0,
    1000,
    3000,
    5000,
    8000,
    10000,
    12000,
]
