seq_name = "gre"
fov_mm = [
    20,
    12,
    12,
]
matrix_size = [
    1000,
    600,
    600,
]
pe_table = "C:/workstation/data/petableCS_stream/stream_CS600_8x_pa18_pb54"
n_pspace_samples = 3
pspace_step_size_mtpm = -50
bandwidth_khz = 200.0
echo_location = 0.1
spoiler_grad_mtpm = 400
rf_pulse_dur_us = 100.0
ramp_time_us = 300.0
pe_dur_us = 600.0
smooth_grad = true
gop_mode = false
sim_mode = false
rep_time_ms = 200.0
post_alpha_del_us = 0.0
post_pe_del_us = 13.0
post_ru_del_us = 50.0
post_acq_del_us = 50.0
grad_limit_tpm = 2.0
